In [104]:
import numpy as np

def np_array_test():
    a = np.array([1, 2, 3])
    print(type(a), ", ", a.shape)
    print(a)
    a[0] = 5
    print(a)
    print(a[0], a[1])
    
    b = np.array([[1, 2, 3], [4, 5, 6]])
    print(type(b), b.shape)
    print(b)
        
def list_test():
    a = [1, 2, 3]
    print(type(a))
    print(a)
    a[0] = 5
    print(a)
    print(a[0], a[1])
    
    b = [[1, 2, 3], [4, 5, 6]]
    print(type(b))
    print(b)

def np_array_test2():
    x = np.array([[1], [2]])
    print("===np.array([1], [2]])\n", x)
    print(x.shape, x.dtype)
    
    x = np.array([1, 2])
    print("===np.array([1, 2])\n", x)
    print(x.shape, x.dtype)
    
np_array_test()
list_test()
np_array_test2()

<class 'numpy.ndarray'> ,  (3,)
[1 2 3]
[5 2 3]
5 2
<class 'numpy.ndarray'> (2, 3)
[[1 2 3]
 [4 5 6]]
<class 'list'>
[1, 2, 3]
[5, 2, 3]
5 2
<class 'list'>
[[1, 2, 3], [4, 5, 6]]
===np.array([1], [2]])
 [[1]
 [2]]
(2, 1) int32
===np.array([1, 2])
 [1 2]
(2,) int32


In [47]:
def np_array_fun_test():
    a = np.zeros((2, 2))
    print("np.zeros((2, 2))\n", a)

    a = np.ones((1, 2))
    print("np.ones((1, 2))\n", a)

    a = np.full((2, 2), 3)
    print("np.full((2, 2), 3)\n", a)  
    
    a = np.eye(2)
    print("np.eye(2)\n", a)  
    
    a = np.random.random((2, 2))
    print("np.random.random((2, 2))\n", a)     
    
np_array_fun_test()  

np.zeros((2, 2))
 [[ 0.  0.]
 [ 0.  0.]]
np.ones((1, 2))
 [[ 1.  1.]]
np.full((2, 2), 3)
 [[3 3]
 [3 3]]
np.eye(2)
 [[ 1.  0.]
 [ 0.  1.]]
np.random.random((2, 2))
 [[ 0.65485321  0.48460722]
 [ 0.5068558   0.15980954]]


In [50]:
def np_array_indexing_test():
    a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    print("a=\n", a)
    b = a[:2, :2]
    print("b=\n", b)
    b[0, 0] = 55
    print("b=\n", b)
    print("a=\n", a)
    
np_array_indexing_test()

a=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b=
 [[1 2]
 [5 6]]
b=
 [[55  2]
 [ 5  6]]
a=
 [[55  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
def np_array_slice_indexing_test():
    a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    
    row1 = a[1, :]      # Rank1
    row2 = a[1:2, :]    # Rank2
    print("=== row slice")
    print(row1, row1.shape)
    print(row2, row2.shape)
    
    col1 = a[:, 1]
    col2 = a[:, 1:2]
    print("=== col slice")
    print(col1, col1.shape)  # Rank1
    print(col2, col2.shape)  # Rank2
    
np_array_slice_indexing_test()

=== row slice
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
=== col slice
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [69]:
def np_array_interger_indexing_test():
    a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    
    print(a)
    print("===indexing\n", a[[0, 1, 2], [0, 1, 2]])
    index = [a[0, 0], a[1, 1], a[2, 2]]
    print("===indexing\n", np.array([index]))
    print("===indexing\n", type(index), index)

np_array_interger_indexing_test()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
===indexing
 [ 1  6 11]
===indexing
 [[ 1  6 11]]
===indexing
 <class 'list'> [1, 6, 11]


In [91]:
def np_array_boolean_indexing():
    a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
    
    print(a)
    
    bool_idx = (a > 5)
    print("===bool_idx\n", bool_idx)

    print("===bool_idx\n", a[bool_idx])
    
    print("===bool_idx\n", a[a > 5])
    
np_array_boolean_indexing()    

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
===bool_idx
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
===bool_idx
 [ 6  7  8  9 10 11 12]
===bool_idx
 [ 6  7  8  9 10 11 12]


In [107]:
def np_array_datatype_test():
    x = np.array([1, 2])
    print(x.dtype)
    
    x = np.array([1., 2.])
    print(x.dtype)
   
    x = np.array([1, 2], dtype=np.int64)
    print(x.dtype)
    
np_array_datatype_test()

int32
float64
int64


In [117]:
def np_array_math_test():
    x = np.array([[1, 2], [3, 4]], dtype=np.float64)
    y = np.array([[1, 2], [3, 4]], dtype=np.float64)
    
    print(x + y)
    print(np.add(x, y))
    
    print(x - y)
    print(np.subtract(x, y))
    
    print(x * y)
    print(np.multiply(x, y))
    
    print(x / y)
    print(np.divide(x, y))
    
    print(np.sqrt(x))
    
np_array_math_test()

[[ 2.  4.]
 [ 6.  8.]]
[[ 2.  4.]
 [ 6.  8.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[  1.   4.]
 [  9.  16.]]
[[  1.   4.]
 [  9.  16.]]
[[ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.]
 [ 1.  1.]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [135]:
def np_array_dot_test():
    x = np.array([[1, 2], [3, 4]])
    y = np.array([[1, 2], [3, 4]])
    print(x.dot(y))       # rank 2 array
    print(np.dot(x, y))
    
    
    v = np.array([1, 2])
    w = np.array([1, 2])
    print("v = ", v, ": shape = ", v.shape)
    print("w = ", w, ": shape = ", w.shape)
    print("v.dot(w) = ", v.dot(w), ": shape = ", (v.dot(w)).shape)       # Inner product of vectors
    print("np.dot(v, w) = ", np.dot(v, w), ": shape = ", (np.dot(v, w)).shape)
    
    print(x.dot(v))       # rank 1 array
    print(np.dot(x, v))
    print(x.shape, v.shape, (np.dot(x, v)).shape)
   
    print(v.dot(x))       # rank 1 array
    print(np.dot(v, x))
    print(v.shape, x.shape, (np.dot(v, x)).shape)
    
np_array_dot_test()


[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
v =  [1 2] : shape =  (2,)
w =  [1 2] : shape =  (2,)
v.dot(w) =  5 : shape =  ()
np.dot(v, w) =  5 : shape =  ()
[ 5 11]
[ 5 11]
(2, 2) (2,) (2,)
[ 7 10]
[ 7 10]
(2,) (2, 2) (2,)


In [ ]:

def np_array_broadcasting_test():
    print("hello")
np_array_broadcasting_test()    